name: Build and deploy container app to Azure Web App - my-apptest123

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mycontainerapp9.azurecr.io/
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mycontainerapp9.azurecr.io/${{ secrets.ACR_USERNAME }}/myapp:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-apptest123"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f916a66907a54d07b2568bf6e509d58b }}
          images: "mycontainerapp9.azurecr.io/${{ secrets.ACR_USERNAME }}/myapp:${{ github.sha }}"
