name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: mycontainerapp9.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t mycontainerapp9.azurecr.io/myapp:latest .
        docker push mycontainerapp9.azurecr.io/myapp:latest

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: my-app-rg
        dns-name-label: eastus
        image-name: mycontainerapp9.azurecr.io/myapp:latest
        container-name: mycontainerapp9
